---
#To download and install percona
- name: To update all packages
  yum:
    name: '*'
    state: latest
  run_once: true
  tags:
    - update

- name: To download tar package of Percona
  get_url:
    url: https://www.percona.com/downloads/Percona-Server-5.6/Percona-Server-5.6.37-82.2/binary/redhat/7/x86_64/Percona-Server-5.6.37-82.2-rd1eb51005df-el7-x86_64-bundle.tar
    dest: /root/

- name: To unarchive  tar packages
  unarchive:
    src: /root/Percona-Server-5.6.37-82.2-rd1eb51005df-el7-x86_64-bundle.tar
    dest: /root/
    remote_src: yes
  tags:
    - archive

- name: To install Percona Server and Client
  yum: name={{ item }} state=present
  with_items:
    - /root/Percona-Server-server-56-5.6.37-rel82.2.el7.x86_64.rpm
    - /root/Percona-Server-client-56-5.6.37-rel82.2.el7.x86_64.rpm
    - /root/Percona-Server-shared-56-5.6.37-rel82.2.el7.x86_64.rpm

- name: To install mysql-python
  yum: name=MySQL-python state=present

- name: To start mysql
  service: name=mysqld state=started

- name: To configure Percona
  include: mysql_secure_installation1.yml

